import budgetApp from '../../assets/budget_App.png';
import airPollutionApp from '../../assets/air_pollution.png';
import purpleCoders from '../../assets/purple_coders.png';
import MathMagician from '../../assets/math.png';
import Restaurant from '../../assets/restaurant.png';
import Docktalk from '../../assets/docktalk.png';
import Space from '../../assets/space.png';

const projectsDone = [
  {
    id: 1,
    title: 'Front_End',
    name: 'Space-Travellers',
    description: 'Project fetches images via API, displaying them on app pages. Users reserve rockets/missions; reservations appear on their profile page.',
    imageSrc: Space,
    btn: '[VIEW BACKEND APPS]',
    technologies: [
      'Redux',
      'React',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'https://space-travellers-one.onrende5r.com/',
    SourceLink: 'https://github.com/Kel-nana/Space-Travellers-Capstone/tree/development',
    date: '2023',
    stack: 'Full End Dev',
  },
  {
    id: 2,
    title: 'Front_End',
    name: 'Math-Magician',
    description: 'is a simple Project built through react npx create-react-app. User can interact by performing the calculator functions.',
    imageSrc: MathMagician,
    btn: '[VIEW BACKEND APPS]',
    technologies: [
      'Redux',
      'React',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'https://math-magician-website-ppor.onrender.com/',
    SourceLink: 'https://github.com/Kel-nana/Budget-app/tree/deployment',
    date: '2023',
    stack: 'Full End Dev',
  },
  {
    id: 3,
    title: 'Front_End',
    name: 'Punjabi food',
    description: 'Punjabi food is a simple project that display sea-foods from TheMealDb Api. The user can like, comment and look the description of each foods.',
    imageSrc: Restaurant,
    btn: '[VIEW BACKEND APPS]',
    technologies: [
      'Jest',
      'Api',
      'JavaScript',
      'Webpack',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'https://lovimadaan.github.io/JavaScript-Capstone/dist/',
    SourceLink: 'https://github.com/Kel-nana/JavaScript-Capstone',
    date: '2023',
    stack: 'Front End Dev',
  },
  {
    id: 4,
    title: 'Front_End',
    name: 'Air Pollution App',
    description: 'A (SPA) web application created with Air Pollution Api, users can check levels of the cities, filter them via dropdown menu and see the details per city on the new page.',
    imageSrc: airPollutionApp,
    btn: '[VIEW BACKEND APPS]',
    technologies: [
      'JavaScript',
      'React/Redux',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'https://air-pollution-mbhw.onrender.com/',
    SourceLink: 'https://github.com/Kel-nana/Air-pollution-capstone-react',
    date: '2023',
    stack: 'Front End Dev',
  },
  {
    id: 5,
    title: 'Front_End',
    name: 'Purple Coders Festival',
    description: 'Purple-Coders is a project meant to master my skills in version control, GitHub flow, pull requests in GitHub and JavaScript.',
    imageSrc: purpleCoders,
    btn: '[VIEW BACKEND APPS]',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'https://kel-nana.github.io/Purple-Coders---HTML-CSS-JavaScript-capstone-project/',
    SourceLink: 'https://github.com/Kel-nana/Purple-Coders---HTML-CSS-JavaScript-capstone-project/tree/HTML-CSS-JavaScript',
    date: '2023',
    stack: 'Front End Dev',
  },
  {
    id: 1,
    title: 'Back_End',
    name: 'DocTalk-App',
    description: 'Doctalk: Your trusted health companion, facilitating informed conversations for better healthcare decisions.',
    imageSrc: Docktalk,
    btn: '[VIEW FRONTEND APPS]',
    technologies: [
      'Rails',
      'Redux',
      'React',
    ],
    liveVersionLink: 'https://doc-talk2.onrender.com/',
    SourceLink: 'https://github.com/Kel-nana/final_group_capstone_front_end/tree/dev',
    date: '2023',
    stack: 'Full Stack Dev',
  },
  {
    id: 2,
    title: 'Back_End',
    name: 'Budget-App',
    description: 'Budget-App: Manage expenses, track spending, and create new groups easily on a mobile web platform.',
    imageSrc: budgetApp,
    btn: '[VIEW FRONTEND APPS]',
    technologies: [
      'JavaScript',
      'Rails',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'https://budget-app-wyrf.onrender.com/',
    SourceLink: 'https://github.com/Kel-nana/Budget-app/tree/deployment',
    date: '2023',
    stack: 'Full Stack Dev',
  },
  {
    id: 3,
    title: 'Back_End',
    name: 'Blog-app',
    description: 'The rails-blog-app: A fully functional blog website where users can interact by commenting and liking posts',
    imageSrc: budgetApp,
    btn: '[VIEW FRONTEND APPS]',
    technologies: [
      'Ruby on Rails',
      'Rails',
      'CSS',
      'HTML',
    ],
    liveVersionLink: 'NOT AVAILABLE',
    SourceLink: 'https://github.com/Kel-nana/Blog-app/tree/dev',
    date: '2023',
    stack: 'Full Stack Dev',
  },
];

export default projectsDone;
